### ISSUE TITLE
Update values of child component with v-money

### ISSUE THREAD

**Issue by Macfuture** [vuejs-tips/v-money#109]
Hello everyone

I’m a Vue newbie and trying to create a webapp to calculate the income and expenses (budget planner).
I use a component with a loop to create the necessary fields. And below there’s a field where I want to calculate the sum of all fields. But I fail to get it to work. I think because the values don’t get updated. The initial values (in data.js) may be not needed, because in the end the initial values will always be zero (the two current values are for testing).

Here you can see simplified app with the problem:
[codesandbox.io/s/v-money-component-test-mltp6](https://codesandbox.io/s/v-money-component-test-mltp6)

How can I update the sum, when a value is changed?
Thanks for you help.

**Comment by jonathanpmartins** [comment]
hey @Macfuture,
Unfortunately I don't think support will come soon. This repo seems to be abandoned! I decided to upgrade this package to be used with Vue3.

Welcome [`v-money3`](https://www.npmjs.com/package/v-money3)!

I'm interested to maintain `v-money3` for **vue 3** and beyond. Feel free to open this same issue [there](https://github.com/jonathanpmartins/v-money3/issues/new) if you are planning to upgrade your project.

**Comment by Macfuture** [comment]
Hi @jonathanpmartins,
Thanks to let me know!
