### ISSUE TITLE
Globally Usage

### ISSUE THREAD

**Issue by gabrielpeixoto** [vuejs-tips/v-money#12]
I am trying to use directive globaly.

`Vue.use(money, {precision: 4});`

` <input v-model.lazy="price" v-money />`

And I got the error: 

>  Error in directive money bind hook: "TypeError: Cannot convert undefined or null to object"

**Comment by gabrielpeixoto** [comment]
I made some changes, and it worked.

`Vue.use(money, {precision: 4});`

`<input v-model.lazy="price" v-money={} />`

Is it the correct usage?

**Comment by neves** [comment]
Fixed with version v0.7.0, now just v-money works

**Comment by luizhenriquerdias** [comment]
Just v-money doesn't work on v0.8.1.
I still need to use v-money={}
