### ISSUE TITLE
How to change value programmatically?

### ISSUE THREAD

**Issue by muratbsts** [vuejs-tips/v-money#14]
Hi, thanks for v-money. But I've a problem. I can't change value programmatically when using as directive. I'm tried like below.

```javascript
...
data() {
    return {
          price: 0.0,
    };
},
...
created() {
     axios.get('blabla').then((res) => { this.price = res.price });
},
...
```

**Comment by neves** [comment]
Here's a example: https://jsfiddle.net/nj3cLoum/3/
But if I set 123 the result became 1,23.
That need to be fixed.

**Comment by muratbsts** [comment]
Can you try with in a promise's resolve function when created() event?

**Comment by neves** [comment]
https://jsfiddle.net/nj3cLoum/4/

**Comment by muratbsts** [comment]
Hi @neves thank you for your answer. But I've still problem. Look:

My input is looking as:
```vue
<input v-model="product.price" v-money="{
    decimal: ',',
    thousands: '.',
    precision: 2,
    masked: false
}" />
````
![image](https://user-images.githubusercontent.com/1137480/28456696-d7d7273a-6e0b-11e7-9371-59ce40261fb3.png)

```javascript
...
data() {
   return {
      product: { price: 0 },
   };
},

created() {
    axios.get('/products/1')
    .then((res) => {
      if (res.data.data) {
        this.product = res.data.data; // { name: 'bar', price: '99.99' }
        // not changing value

        // mm, try with a method
        this.setPrice(res.data.data.price);
        // not changing

        // look at product.price, it's correct
        console.log(this.product.price); // 99.99
      }
    });

    // tried like as following
    this.setPrice(123456);
    // weird, changed value to 1.234,56
},


methods: {
    setPrice(price) {
      this.product.price = price;
    },
}
...
```

Not: I apologize if I say something ridiculous because my english is not very good.

**Comment by neves** [comment]
You are probably having some issues with axios, try to put console.log(res) after .then.
But the value 123456 became 1.234,56 need to be fixed.

**Comment by muratbsts** [comment]
I've found problem. I'm using element ui. This problem related el-input component. There isn't a problem if I use html input element. Thanks for your interest @neves

**Comment by ardifirmansyah8** [comment]
@muratbsts how you solve this in element ui? i cant changed the value too

**Comment by murat** [comment]
@ardifirmansyah8 I stopped use v-money with el-input both. I'm using as the directive.

**Comment by albayraktaroglu** [comment]
I had the same issue I see that the component can't hold the .00 precisions. 

Ex: 
if our variable is 1.00 Js interpret as 1 rather than keeping it like 1.00 but we can't say the same thing for precisions with other values like 1.23 is interpreted as 1.23 

So seems like currently, the component can handle the case if you are holding your variable as strings. "1.00"  is displayed correctly.

https://jsfiddle.net/nj3cLoum/1124/
