### ISSUE TITLE
on input:focus bug?

### ISSUE THREAD

**Issue by nmkr** [vuejs-tips/v-money#19]
hey,

testet the demo: https://jsfiddle.net/auom8st8/
if we click in the input the cursor jumps to the last position.

is this a feature or bug?

regards

**Comment by neves** [comment]
That was implemented as a feature so the user can start typing in the correct place.

**Comment by thedamon** [comment]
"correct place" ? if the user wanted to type at the end maybe they would have clicked at the end. other inputs do not function this way, and is very difficult to change 100000000000 to 100200000000....

**Comment by vientoquesurcalosmares** [comment]
> 
> 
> "correct place" ? if the user wanted to type at the end maybe they would have clicked at the end. other inputs do not function this way, and is very difficult to change 100000000000 to 100200000000....

I agree with you, this is a problem for the user
