### ISSUE TITLE
Options has no effect when registering global component

### ISSUE THREAD

**Issue by ankurk91** [vuejs-tips/v-money#23]
According to README, we can pass config options like this
```js
Vue.use(money, {precision: 4})
```
But actually this has no effect. I have tried passing other options as well.
```js
import Vue from 'vue';
import money from 'v-money';

// Register global directive v-money and component <money>
Vue.use(money, {
  prefix: '$',
  suffix: '',
  thousands: ',',
  decimal: '.',
  precision: 0
});
```
```html
<money v-model="price">
```
But no luck, i need to pass options to each component like this-
```js
<money v-model="price" v-bind="{precision:0}">
```

Vue v2.4.2
v-money v0.8.0

Let me know if i am missing something.

**Comment by mrabdolian** [comment]
I have the exact same problem!
Did you find a solution?
If yes, please share with us. 🙏🏻

We're using "nuxt v2.2.0" and "v-currency-field v1.0.5" (that is built based on v-money).

Thanks.
