### ISSUE TITLE
Not working with nuxt?

### ISSUE THREAD

**Issue by cannap** [vuejs-tips/v-money#39]
HI i try to use this plugin with nuxt but when i say

plugins/vue-money.js
```js
import Vue from 'vue'
// import { VMoney } from 'vue-money'
import money from 'vue-money'
console.log(money)
Vue.use(money, { precision: 4 })
// Vue.directive('money', VMoney)
```
nuxt.config.js

```js
plugins: [{ src: '~/plugins/vue-money.js' }],
```
Directive is not defined and component are not registerd

i tried in <no-ssr></no-ssr>

i dont know where the problem is on nuxt side or on this component :P
Solved i installed vue-money and not v-money

**Comment by mesqueeb** [comment]
Did you disable srr in Nuxt settings?

**Comment by cannap** [comment]
@mesqueeb no i installed the wrong package :D

**Comment by mesqueeb** [comment]
`v-money` is the correct package. This Github page is for `v-money`.
