### ISSUE TITLE
directive usage

### ISSUE THREAD

**Issue by shrpne** [vuejs-tips/v-money#4]
I'm trying to use v-money as directive and get error `[Vue warn]: Failed to resolve directive: money`
I use example from docs https://github.com/vuejs-tips/v-money#c-use-as-directive-httpsjsfiddlenetauom8st8

Also links to jsfiddle in component and directive examples are same.

**Comment by shrpne** [comment]
I realized, that it can be fixed with this directive declaration:
`directives: {money: VMoney}` 


I have one more question, why `v-model.lazy` is necessary? Looks like it works well with `v-model` too.

**Comment by neves** [comment]
`v-model.lazy` is necessary for some edge cases, but 99% of time v-model alone is enough.
`masked: false` can't work with directive because it can't intercept the input event. In that case, you have to unformat yourself using the function `unformat` from `utils.js`

**Comment by shrpne** [comment]
How about put `unformat` not into vue's `@change` attribute, but into native js event handler?

**Comment by neves** [comment]
@shrpne unfortunately the event that vue listen is a different one from mine. But I'm would like to find a solution for this problem.

**Comment by akarelas** [comment]
Will you fix the documentation of directives: {VMoney} ?

**Comment by neves** [comment]
Fixed documentation #10
