### ISSUE TITLE
Trigger @change event

### ISSUE THREAD

**Issue by Arwany** [vuejs-tips/v-money#42]
Hi,

how can I make the input trigger a change event? I want to make something like this:

```
<money id="val" name="val" class="form-control" v-model="val" v-bind="settings" @change="setSomethingElse"></money>


--The javascript looks like this:

val: 0,
settings: {
            decimal: ',',
            thousands: '',
            prefix: '',
            suffix: '',
            precision: 0,
            masked: false
},

....
setSomethingElse(){
// Do something here
},

```

This did not work, which I suppose is not supported right now...

Thank you!

**Comment by neves** [comment]
Did you try `@change.native`

**Comment by Arwany** [comment]
Thank you @neves  for your answer. I will give it a try and report back (close this issue if it solved my problem).

**Comment by Arwany** [comment]
This worked, thank you!

**Comment by EdnaldoNeimeg** [comment]
Should be in docs :(

**Comment by williampaulo** [comment]
Hello, I tried to use @ change.native, but for each digit the method is called 3 times

**Comment by liuyao61** [comment]
+1 @ change.native trigger the method 3 times every change

**Comment by liuyao61** [comment]
@williampaulo I use @blur.native and it works for my purpose.

**Comment by omerciftcibasi** [comment]
@williampaulo thanx for workaround, however it should trigger the change event only one time.

**Comment by rayanmarcus** [comment]
> @williampaulo I use `@blur.native` and it works for my purpose.

This works for me. Using `@ change.native` the event was called 3x.

**Comment by AleejandroReyna** [comment]
In my case, @change.native is executed x24 times :(

**Comment by tuxpedro** [comment]
In my case `@blur.native` solved the problem. when I used `@input`, `@change` or `@change.native` created an infinite loop in my application.
