### ISSUE TITLE
opinionated styles

### ISSUE THREAD

**Issue by shrpne** [vuejs-tips/v-money#5]
v-money apply `style="text-align: right;"`
If someone need it, it can be styled very easy. But if not, it not so easy to remove this style.

I think v-money should be about how things work, but not how things look.
So I think it should be removed.

**Comment by kleinernik** [comment]
Remove is easy, just put `style="text-align: left;"` on your money element. Still the general remark about not beeing opinionated may be valid.

**Comment by neves** [comment]
I was worried about it when I made that decision, but I think it's way more used aligned to right than left, and it's not that hard to override it using inline style or css !important.
But I'm still open for discussion.

**Comment by shrpne** [comment]
Aligning currency to the right make sense for tables, but in forms usually money inputs aligned as other inputs in the form, especially if form has vertical layout.

Also common approach for styling is css classes, in this case inline styles or !important is a bad practice.

**Comment by neves** [comment]
What if I remove the style and add a class `v-money` to make it easy to style globally.
Do you think it would still be too opinionated?

**Comment by shrpne** [comment]
At least classes will be easier to override.
Still, I would prefer that there were no default styles.
I think applying styles will be good for fully styled components, like vuetify
But v-money looks like component, which just adds functionality and needs to be styled.
If it needs to be styled, why add single default style rule? It seems a bit weird.

**Comment by neves** [comment]
My suggestion is to have a class named `v-money` and that's all, no default style.
So, if someone want to align right, they can create a global style like:
`.v-money { text-align: right; }`

**Comment by shrpne** [comment]
I think it's fine

**Comment by neves** [comment]
Fixed with version v0.7.0. Thanks for helping.
