### ISSUE TITLE
Negative Values (minus signal)

### ISSUE THREAD

**Issue by dgranzotto** [vuejs-tips/v-money#6]
Are there any way to work with negative values (pressing the minus key) ?
Thanks a lot.

**Comment by neves** [comment]
I'm thinking how to implement that.

**Comment by neves** [comment]
Fixed with version 0.8.0
thanks for reporting.

**Comment by obelich** [comment]
how i can block the negative ?

**Comment by xdeq** [comment]
> how i can block the negative ?
@obelich 

`@keydown="$event.key === '-' && $event.preventDefault()"`
