### ISSUE TITLE
Instead of blank fields being 0, can they be blank?

### ISSUE THREAD

**Issue by andrewevans** [vuejs-tips/v-money#65]
I have added a short circuit on `format()` and `unformat()` to return the input as an empty string if that's what it is. The current behavior changes empty string `''` into `0`. I can do a PR if this is a desired feature.

**Comment by nholden** [comment]
Hi, @andrewevans! I think my PR https://github.com/vuejs-tips/v-money/pull/51 addresses what you've noticed.

**Comment by andrewevans** [comment]
Yes it completely does. Closing this issue.
